<html lang="<?php echo $this->getLang() ?>">
    <head>
    <?php echo $this->getChildHtml('head') ?>
    </head>
    <body>
    <?php echo $this->getChildHtml('after_body_start') ?>
    <div class="wrapper">
        <div class="page">
            <?php echo $this->getChildHtml('header') ?>
            <div class="main-container col1-layout">
                <div class="main">
                    <div class="col-main">
                        <?php echo $this->getChildHtml('content') ?>
                    </div>
                </div>
            </div>
            <?php echo $this->getChildHtml('footer') ?>
            <?php echo $this->getChildHtml('before_body_end') ?>
        </div>
    </div>
    <?php echo $this->getAbsoluteFooter() ?>
    </body>
    </html>